// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProg_Projekat_2021.Models;

namespace WebProg_Projekat_2021.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProg_Projekat_2021.Models.Mesto", b =>
                {
                    b.Property<int>("MestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MestoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj")
                        .HasColumnType("int")
                        .HasColumnName("Broj");

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("MestoId");

                    b.HasIndex("ParkingId");

                    b.HasIndex("VoziloId");

                    b.ToTable("Mesto");
                });

            modelBuilder.Entity("WebProg_Projekat_2021.Models.Parking", b =>
                {
                    b.Property<int>("ParkingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("ParkingId");

                    b.ToTable("Parking");
                });

            modelBuilder.Entity("WebProg_Projekat_2021.Models.Vozilo", b =>
                {
                    b.Property<int>("VoziloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoziloId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Boja");

                    b.Property<int>("Godiste")
                        .HasColumnType("int")
                        .HasColumnName("Godiste");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Marka");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tip");

                    b.HasKey("VoziloId");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("WebProg_Projekat_2021.Models.Mesto", b =>
                {
                    b.HasOne("WebProg_Projekat_2021.Models.Parking", "Parking")
                        .WithMany("Mesta")
                        .HasForeignKey("ParkingId");

                    b.HasOne("WebProg_Projekat_2021.Models.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloId");

                    b.Navigation("Parking");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("WebProg_Projekat_2021.Models.Parking", b =>
                {
                    b.Navigation("Mesta");
                });
#pragma warning restore 612, 618
        }
    }
}
